# Generated by Django 5.0.3 on 2025-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите на оплату товара",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату товара",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Введите Id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
    ]
